### PR TITLE
Fixed minor spelling errors

### PR DESCRIPTION
**Pull request by damienwolf07**
Just fixed 2 words, Minor spelling errors.

### CODE REVIEW

**Review by G6EJD — APPROVED** [review]

**Review by G6EJD — APPROVED** [review]

**Comment by G6EJD** [comment]
Thank you

**Comment by damienwolf07** [comment]
> Thank you

Oops! I think you may of closed the pull request instead of merge 😸

**Comment by G6EJD** [comment]
It has updated but not updated the date of the file?

**Comment by damienwolf07** [comment]
> It has updated but not updated the date of the file?

While yes you did approve the changes you closed the merge meaning that the changes didn't get applied to main, I can re-open another pull request if you can't merge it, I think you closed it as if it were a issue post, If you need me to create another one just let me know!

**Comment by G6EJD** [comment]
Everything seems to be correct now.

**Pull request closed without merging**
